# Generated by Django 5.2.16 on 2026-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobcardphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Completion Time'),
        ),
    ]
