# Generated by Django 5.2.16 on 2026-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobcard_estimated_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Vehicle Photo'),
        ),
    ]
