# Generated by Django 5.2.16 on 2026-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Custom Role Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('advisor', 'Service Advisor'), ('mechanic', 'Mechanic'), ('store_manager', 'Store Manager'), ('custom', 'Custom Role')], default='mechanic', max_length=50),
        ),
    ]
