# Generated by Django 5.2.16 on 2026-08-08 04:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_custom_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_pickup_service',
            field=models.BooleanField(default=False, verbose_name='Vehicle Pickup & Drop Service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pickup_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pickup & Drop Charge'),
        ),
    ]
