# Generated by Django 5.2.16 on 2026-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rolecustomization'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Krishna Auto Care', max_length=150, verbose_name='Garage / Workshop Name')),
                ('tagline', models.CharField(blank=True, default='Precision Workshop', max_length=200, verbose_name='Tagline / Subtitle')),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=30, verbose_name='Contact Phone')),
                ('email', models.EmailField(blank=True, default='info@krishnaautocare.com', max_length=254, verbose_name='Contact Email')),
                ('address', models.TextField(blank=True, default='Main Road, Near Bus Stand', verbose_name='Street Address')),
                ('city', models.CharField(blank=True, default='Kochi', max_length=100, verbose_name='City / Place')),
                ('state', models.CharField(blank=True, default='Kerala', max_length=100, verbose_name='State')),
                ('pincode', models.CharField(blank=True, default='682001', max_length=20, verbose_name='Pincode / Zip')),
                ('gst_number', models.CharField(blank=True, max_length=50, verbose_name='GST / Tax ID Number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='garage/', verbose_name='Garage Logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
