# Generated by Django 5.2.16 on 2026-08-12 07:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_garagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Labour/Service Discount %'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amc_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='AMC Discount Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amc_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.customeramc'),
        ),
    ]
