# Generated by Django 5.2.16 on 2026-08-19 11:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_amcplan_discount_percentage_invoice_amc_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active Plan'),
        ),
        migrations.AddField(
            model_name='amcplan',
            name='service_interval_months',
            field=models.PositiveIntegerField(default=3, verbose_name='Service Interval (Months)'),
        ),
        migrations.AddField(
            model_name='amcplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='amcserviceschedule',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='previous_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='core.customeramc'),
        ),
        migrations.AddField(
            model_name='customeramc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='amc_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='core.amcserviceschedule'),
        ),
        migrations.AlterField(
            model_name='amcserviceschedule',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_schedules', to='core.jobcard'),
        ),
        migrations.AlterField(
            model_name='amcserviceschedule',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='upcoming', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customeramc',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
